Repository Macro-Deck-App/Macro-Deck, pull requests merged in 2023-10, with the labels that each got.

#448 Fix extension updates
  MacroDeck/ExtensionStore/ExtensionStoreHelper.cs
  MacroDeck/GUI/CustomControls/ExtensionStoreDownloader/ExtensionStoreDownloaderItem.cs
  MacroDeck/GUI/CustomControls/ExtensionsView/ExtensionStoreItemView.cs
  MacroDeck/Icons/IconManager.cs
  MacroDeck/Plugins/PluginManager.cs
Labels: bug

#449 Improve extension store
  MacroDeck/GUI/CustomControls/ExtensionsView/ExtensionStoreView.cs
Labels: improvement

#451 Remove old dependencies
  MacroDeck.Tests/MacroDeck.Tests.csproj
  MacroDeck.Tests/Usings.cs
  MacroDeck/ActionButton/ActionButton.cs
  MacroDeck/ActionButton/ConditionAction.cs
  MacroDeck/Events/EventListener.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/ActionItem.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/ActionSelectorOnPress.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/ConditionItem.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/DelayItem.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/EventItem.cs
  MacroDeck/GUI/CustomControls/ContentSelectorButton.Designer.cs
  MacroDeck/GUI/CustomControls/ContentSelectorButton.cs
  MacroDeck/GUI/CustomControls/ExtensionsView/ExtensionStoreItemView.cs
  MacroDeck/GUI/CustomControls/Form.Designer.cs
  MacroDeck/GUI/CustomControls/Form.cs
  MacroDeck/GUI/Dialogs/ActionConfigurator.cs
  MacroDeck/GUI/Dialogs/ButtonEditor.Designer.cs
  MacroDeck/GUI/Dialogs/ButtonEditor.cs
  MacroDeck/GUI/Dialogs/GiphySelector.Designer.cs
  MacroDeck/GUI/Dialogs/GiphySelector.cs
  MacroDeck/GUI/Dialogs/GiphySelector.resx
  MacroDeck/GUI/Dialogs/IconSelector.Designer.cs
  MacroDeck/GUI/Dialogs/IconSelector.cs
  MacroDeck/GUI/MainWindow.Designer.cs
  MacroDeck/GUI/MainWindow.cs
  MacroDeck/GUI/MainWindowViews/DeviceManagerView.cs
  MacroDeck/Interfaces/IActionConditionItem.cs
  MacroDeck/MacroDeck.cs
  MacroDeck/MacroDeck.csproj
  MacroDeck/Plugins/MacroDeckPlugin.cs
  MacroDeck/Plugins/PluginManager.cs
  MacroDeck/Profiles/ProfileManager.cs
  MacroDeck/Server/MacroDeckServer.cs
  MacroDeck/Variables/VariableManager.cs
Labels: dependencies

#450 Improve performance
  MacroDeck/ActionButton/ActionButton.cs
  MacroDeck/ActionButton/ConditionAction.cs
  MacroDeck/Events/EventListener.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/ActionItem.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/ActionSelectorOnPress.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/ConditionItem.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/DelayItem.cs
  MacroDeck/GUI/CustomControls/ButtonEditor/EventItem.cs
  MacroDeck/GUI/CustomControls/ContentSelectorButton.Designer.cs
  MacroDeck/GUI/CustomControls/ContentSelectorButton.cs
  MacroDeck/GUI/CustomControls/ExtensionsView/ExtensionStoreItemView.cs
  MacroDeck/GUI/CustomControls/Form.Designer.cs
  MacroDeck/GUI/CustomControls/Form.cs
  MacroDeck/GUI/Dialogs/ActionConfigurator.cs
  MacroDeck/GUI/Dialogs/ButtonEditor.Designer.cs
  MacroDeck/GUI/Dialogs/ButtonEditor.cs
  MacroDeck/GUI/Dialogs/IconSelector.Designer.cs
  MacroDeck/GUI/Dialogs/IconSelector.cs
  MacroDeck/GUI/MainWindow.Designer.cs
  MacroDeck/GUI/MainWindow.cs
  MacroDeck/GUI/MainWindowViews/DeviceManagerView.cs
  MacroDeck/Interfaces/IActionConditionItem.cs
  MacroDeck/MacroDeck.cs
  MacroDeck/Plugins/MacroDeckPlugin.cs
  MacroDeck/Plugins/PluginManager.cs
  MacroDeck/Profiles/ProfileManager.cs
  MacroDeck/Server/MacroDeckServer.cs
  MacroDeck/Variables/VariableManager.cs
Labels: improvement

#453 Fix icon import
  MacroDeck/GUI/Dialogs/IconSelector.Designer.cs
  MacroDeck/GUI/Dialogs/IconSelector.cs
Labels: bug

#454 Fix internal plugins not enabled
  MacroDeck/Plugins/PluginManager.cs
Labels: bug

#455 Fix folder delete child folders
  MacroDeck/Profiles/ProfileManager.cs
Labels: bug

#457 fix adb client error: address is not valid
  MacroDeck/Server/ADBServerHelper.cs
Labels: bug

#459 Refactor websocket
  Directory.Build.props
  MacroDeck.Server/Controllers/PingController.cs
  MacroDeck.Server/Controllers/WebSocketController.cs
  MacroDeck.Server/DataTypes/PingResponse.cs
  MacroDeck.Server/DataTypes/WebSocketCloseReason.cs
  MacroDeck.Server/DataTypes/WebSocketNormalClose.cs
  MacroDeck.Server/DataTypes/WebSocketSession.cs
  MacroDeck.Server/MacroDeck.Server.csproj
  MacroDeck.Server/MacroDeckServerHelper.cs
  MacroDeck.Server/Startup.cs
  MacroDeck.Server/StartupConfig/ApiControllerConfig.cs
  MacroDeck.Server/WebSocketHandler.cs
  MacroDeck.Tests/MacroDeck.Tests.csproj
  MacroDeck.sln
  MacroDeck/CottleIntegration/TemplateManager.cs
  MacroDeck/Device/DeviceManager.cs
  MacroDeck/Device/MacroDeckDevice.cs
  MacroDeck/Extension/DoubleExtensions.cs
  MacroDeck/Extension/LongExtensions.cs
  MacroDeck/Extension/StreamExtensions.cs
  MacroDeck/ExtensionStore/ExtensionStoreHelper.cs
  MacroDeck/GUI/CustomControls/DeviceInfo.cs
  MacroDeck/GUI/CustomControls/ExtensionStoreDownloader/ExtensionStoreDownloaderItem.cs
  MacroDeck/GUI/CustomControls/ExtensionsView/ExtensionStoreItemView.cs
  MacroDeck/GUI/Dialogs/NewConnectionDialog.Designer.cs
  MacroDeck/GUI/Dialogs/NewConnectionDialog.cs
  MacroDeck/GUI/MainWindow.Designer.cs
  MacroDeck/GUI/MainWindow.cs
  MacroDeck/GUI/MainWindowViews/SettingsView.cs
  MacroDeck/Icons/IconManager.cs
  MacroDeck/InternalPlugins/Variables/VariablesPlugin.cs
  MacroDeck/MacroDeck.cs
  MacroDeck/MacroDeck.csproj
  MacroDeck/Models/ApiV2ExtensionFile.cs
  MacroDeck/Models/PagedList.cs
  MacroDeck/Plugins/PluginManager.cs
  MacroDeck/Server/BroadcastServer.cs
  MacroDeck/Server/DeviceMessage/SoftwareClientMessage.cs
  MacroDeck/Server/MacroDeckClient.cs
  MacroDeck/Server/MacroDeckServer.cs
  MacroDeck/Utils/FileDownloader.cs
  MacroDeck/Variables/VariableManager.cs
  MacroDeck/wwwroot/client/index.html
Labels: feature

#458 Minor refactoring of BackupManager
  MacroDeck/Backup/BackupManager.cs
Labels: improvement

#460 Add SSL support
  Directory.Packages.props
  MacroDeck.Server/MacroDeck.Server.csproj
  MacroDeck.Server/MacroDeckServerHelper.cs
  MacroDeck.Tests/MacroDeck.Tests.csproj
  MacroDeck.sln
  MacroDeck/Configuration/MainConfiguration.cs
  MacroDeck/GUI/Dialogs/ExtensionStoreDownloader.cs
  MacroDeck/GUI/MainWindowViews/SettingsView.Designer.cs
  MacroDeck/GUI/MainWindowViews/SettingsView.cs
  MacroDeck/GUI/MainWindowViews/SettingsView.resx
  MacroDeck/MacroDeck.cs
  MacroDeck/MacroDeck.csproj
  MacroDeck/Resources/Languages/English.json
  MacroDeck/Resources/Languages/German.json
  MacroDeck/Server/MacroDeckServer.cs
Labels: feature

#462 Add web client
  .github/workflows/pull-web-client.yml
  MacroDeck.Server/Controllers/WebSocketController.cs
  MacroDeck.Server/MacroDeckServerHelper.cs
  MacroDeck.Server/Startup.cs
  MacroDeck.Setup/Macro Deck.iss
  MacroDeck.sln
  MacroDeck/MacroDeck.csproj
Labels: feature

#466 Add self-hosted web client
  MacroDeck.Server/Controllers/WebSocketController.cs
Labels: feature
