Repository Macro-Deck-App/Macro-Deck, pull requests merged in 2024-05, with the labels that each got.

#524 Add option to enable and disable ADB + Improve ADB service for USB connection
  Directory.Packages.props
  MacroDeck/Configuration/MainConfiguration.cs
  MacroDeck/GUI/MainWindowViews/SettingsView.Designer.cs
  MacroDeck/GUI/MainWindowViews/SettingsView.cs
  MacroDeck/GUI/MainWindowViews/SettingsView.resx
  MacroDeck/MacroDeck.cs
  MacroDeck/MacroDeck.csproj
  MacroDeck/Program.cs
  MacroDeck/Server/ADBServerHelper.cs
  MacroDeck/Server/AdbServerHelper.cs
Labels: feature

#525 Add QR Code for Quick Setup
  Directory.Packages.props
  MacroDeck/DataTypes/QrCode/QuickConnectQrCodeData.cs
  MacroDeck/GUI/MainWindow.Designer.cs
  MacroDeck/GUI/MainWindow.cs
  MacroDeck/GUI/MainWindow.resx
  MacroDeck/MacroDeck.csproj
  MacroDeck/Services/QrCodeService.cs
Labels: feature

#528 Replace custom window frame with Windows window frame
  MacroDeck/ActionButton/ActionButton.cs
  MacroDeck/GUI/CustomControls/ButtonPrimary.cs
  MacroDeck/GUI/CustomControls/DialogForm.Designer.cs
  MacroDeck/GUI/CustomControls/DialogForm.cs
  MacroDeck/GUI/CustomControls/DialogForm.resx
  MacroDeck/GUI/CustomControls/Form.Designer.cs
  MacroDeck/GUI/CustomControls/Form.cs
  MacroDeck/GUI/CustomControls/MessageBox.Designer.cs
  MacroDeck/GUI/CustomControls/MessageBox.resx
  MacroDeck/GUI/Dialogs/CreateIconPack.Designer.cs
  MacroDeck/GUI/Dialogs/CreateIconPack.resx
  MacroDeck/GUI/Dialogs/CreateProfileDialog.Designer.cs
  MacroDeck/GUI/Dialogs/CreateProfileDialog.resx
  MacroDeck/GUI/Dialogs/DefenderFirewallAlert.Designer.cs
  MacroDeck/GUI/Dialogs/DefenderFirewallAlert.resx
  MacroDeck/GUI/Dialogs/ExportIconPackDialog.Designer.cs
  MacroDeck/GUI/Dialogs/ExportIconPackDialog.resx
  MacroDeck/GUI/Dialogs/ExtensionStoreDownloader.Designer.cs
  MacroDeck/GUI/Dialogs/ExtensionStoreDownloader.resx
  MacroDeck/GUI/Dialogs/IconCreator.Designer.cs
  MacroDeck/GUI/Dialogs/IconCreator.resx
  MacroDeck/GUI/Dialogs/IconImportQuality.Designer.cs
  MacroDeck/GUI/Dialogs/IconImportQuality.resx
  MacroDeck/GUI/Dialogs/JsonButtonEditor.Designer.cs
  MacroDeck/GUI/Dialogs/JsonButtonEditor.resx
  MacroDeck/GUI/Dialogs/LicensesDialog.Designer.cs
  MacroDeck/GUI/Dialogs/LicensesDialog.resx
  MacroDeck/GUI/Dialogs/RestoreBackupDialog.Designer.cs
  MacroDeck/GUI/Dialogs/RestoreBackupDialog.resx
  MacroDeck/GUI/Dialogs/TemplateEditor.Designer.cs
  MacroDeck/GUI/Dialogs/TemplateEditor.resx
  MacroDeck/GUI/Dialogs/UpdateAvailableDialog.Designer.cs
  MacroDeck/GUI/Dialogs/UpdateAvailableDialog.resx
  MacroDeck/GUI/Dialogs/VariableDialog.Designer.cs
  MacroDeck/GUI/Dialogs/VariableDialog.resx
  MacroDeck/GUI/Dialogs/WaitDialog.Designer.cs
  MacroDeck/GUI/Dialogs/WaitDialog.resx
  MacroDeck/GUI/InitialSetup.Designer.cs
  MacroDeck/GUI/InitialSetup.resx
  MacroDeck/GUI/MainWindow.Designer.cs
  MacroDeck/GUI/MainWindow.cs
  MacroDeck/GUI/MainWindowViews/DeckView.Designer.cs
  MacroDeck/GUI/MainWindowViews/DeckView.cs
  MacroDeck/Icons/IconLegacy.cs
  MacroDeck/Icons/IconManagerLegacy.cs
  MacroDeck/Icons/IconPackLegacy.cs
  MacroDeck/Server/MacroDeckClient.cs
  MacroDeck/Server/MacroDeckServer.cs
  MacroDeck/Variables/VariableManager.cs
Labels: improvement

#529 Fix crash on pipe timeout
  MacroDeck/MacroDeck.cs
  MacroDeck/Pipe/MacroDeckPipeClient.cs
  MacroDeck/Pipe/MacroDeckPipeServer.cs
  MacroDeck/Program.cs
Labels: bug

#534 Add option to toggle Quick Setup QR code
  MacroDeck/App.config
  MacroDeck/DataTypes/QrCode/QuickConnectQrCodeData.cs
  MacroDeck/GUI/CustomControls/Form.cs
  MacroDeck/GUI/MainWindowViews/DeckView.Designer.cs
  MacroDeck/GUI/MainWindowViews/DeckView.cs
  MacroDeck/Properties/Settings.Designer.cs
  MacroDeck/Properties/Settings.settings
  MacroDeck/Services/QrCodeService.cs
  MacroDeck/Utils/NetworkUtils.cs
Labels: improvement

#533 Updated Spanish Translation
  .github/workflows/create-release.yml
  MacroDeck/MacroDeck.csproj
  MacroDeck/Resources/Languages/Spanish.json
Labels: improvement
